# Generated by Django 3.2.3 on 2021-06-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemprojeto',
            name='url',
            field=models.URLField(default=2, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
