# Generated by Django 3.2.3 on 2021-06-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagemprojeto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemprojeto',
            name='url',
        ),
    ]
