# Generated by Django 3.2.3 on 2021-06-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_imagemprojeto_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagemProjeto',
        ),
    ]
